name: 📋 Task
description: Create a new task with description and acceptance criteria
title: "[TASK]: "
labels: [task]

body:
  - type: markdown
    attributes:
      value: |
        ## Task Description
        Please provide details of the task.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
      placeholder: Describe the task context, scope, and purpose
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the conditions that must be met for this task to be considered complete
      placeholder: |
        Example:
        - [ ] Documentation updated
        - [ ] Code changes reviewed and merged
        - [ ] Tests passing
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Links, dependencies, or extra notes
